---
title: "CK 2.2_3.1 Summary of Initial Answers (Winter 2021)"
author: "Rachel Roggenkemper"
date: '2022-08-09'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("~/Documents/FROST-SUMMER-2022/Winter2021")

library(tidyverse)
library(readxl)  
CK2.2_3.1 <- read_excel("FROST Grading CK 2.2_3.1_final (Winter 2021).xlsx")
```

```{r}
CK2.2_3.1_clean = subset(CK2.2_3.1, select = -c(Student:GroupCK.2.2_3.1))

CK2.2_3.1_clean <- drop_na(CK2.2_3.1_clean)
```

```{r}
CK2.2_3.1_all <- data.frame(unlist(CK2.2_3.1_clean))
colnames(CK2.2_3.1_all)[1] <- "Grades"
```


All Questions 
```{r}
CK2.2_3.1_all %>%
  count(Grades)
```

```{r}
CK2.2_3.1_all %>%
  ggplot() +
  geom_bar(aes(x = Grades))
```


Question 5
```{r}
CK2.2_3.1_clean %>%
  count(Q5.Grade)
```

```{r}
CK2.2_3.1_clean %>%
  ggplot() +
  geom_bar(aes(x = Q5.Grade))
```


Question 6
```{r}
CK2.2_3.1_clean %>%
  count(Q6.Grade)
```

```{r}
CK2.2_3.1_clean %>%
  ggplot() +
  geom_bar(aes(x = Q6.Grade))
```


Question 14
```{r}
CK2.2_3.1_clean %>%
  count(Q14.Grade)
```

```{r}
CK2.2_3.1_clean %>%
  ggplot() +
  geom_bar(aes(x = Q14.Grade))
```


Question 3
```{r}
CK2.2_3.1_clean %>%
  count(Q3.Grade)
```

```{r}
CK2.2_3.1_clean %>%
  ggplot() +
  geom_bar(aes(x = Q3.Grade))
```


Question 7
```{r}
CK2.2_3.1_clean %>%
  count(Q7.Grade)
```

```{r}
CK2.2_3.1_clean %>%
  ggplot() +
  geom_bar(aes(x = Q7.Grade))
```


Question 11
```{r}
CK2.2_3.1_clean %>%
  count(Q11.Grade)
```

```{r}
CK2.2_3.1_clean %>%
  ggplot() +
  geom_bar(aes(x = Q11.Grade))
```


Question 12
```{r}
CK2.2_3.1_clean %>%
  count(Q12.Grade)
```

```{r}
CK2.2_3.1_clean %>%
  ggplot() +
  geom_bar(aes(x = Q12.Grade))
```


Question 13
```{r}
CK2.2_3.1_clean %>%
  count(Q13.Grade)
```

```{r}
CK2.2_3.1_clean %>%
  ggplot() +
  geom_bar(aes(x = Q13.Grade))
```


