---
title: "CK 2.1 Summary of Initial Answers (Winter 2021)"
author: "Rachel Roggenkemper"
date: '2022-08-09'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("~/Documents/FROST-SUMMER-2022/Winter2021")

library(tidyverse)
library(readxl)  
CK2.1 <- read_excel("FROST Grading CK 2.1_final (Winter 2021).xlsx")
CK2.1_clean <- select(CK2.1, c(1:4, 197:206))
```

```{r}
CK2.1_clean = subset(CK2.1_clean, select = -c(Student:GroupCK.2.1))

CK2.1_clean <- drop_na(CK2.1_clean)
```

```{r}
CK2.1_all <- data.frame(unlist(CK2.1_clean))
colnames(CK2.1_all)[1] <- "Grades"
```


All Questions 
```{r}
CK2.1_all %>%
  count(Grades)
```

```{r}
CK2.1_all %>%
  ggplot() +
  geom_bar(aes(x = Grades))
```


Question 6
```{r}
CK2.1_clean %>%
  count(Q6.Grade)
```

```{r}
CK2.1_clean %>%
  ggplot() +
  geom_bar(aes(x = Q6.Grade))
```


Question 7
```{r}
CK2.1_clean %>%
  count(Q7.Grade)
```

```{r}
CK2.1_clean %>%
  ggplot() +
  geom_bar(aes(x = Q7.Grade))
```


Question 12
```{r}
CK2.1_clean %>%
  count(Q12.Grade)
```

```{r}
CK2.1_clean %>%
  ggplot() +
  geom_bar(aes(x = Q12.Grade))
```


Question 14
```{r}
CK2.1_clean %>%
  count(Q14.Grade)
```

```{r}
CK2.1_clean %>%
  ggplot() +
  geom_bar(aes(x = Q14.Grade))
```


Question 26
```{r}
CK2.1_clean %>%
  count(Q26.Grade)
```

```{r}
CK2.1_clean %>%
  ggplot() +
  geom_bar(aes(x = Q26.Grade))
```


Question 28
```{r}
CK2.1_clean %>%
  count(Q28.Grade)
```

```{r}
CK2.1_clean %>%
  ggplot() +
  geom_bar(aes(x = Q28.Grade))
```


Question 31
```{r}
CK2.1_clean %>%
  count(Q31.Grade)
```

```{r}
CK2.1_clean %>%
  ggplot() +
  geom_bar(aes(x = Q31.Grade))
```


Question 34
```{r}
CK2.1_clean %>%
  count(Q34.Grade)
```

```{r}
CK2.1_clean %>%
  ggplot() +
  geom_bar(aes(x = Q34.Grade))
```


Question 36
```{r}
CK2.1_clean %>%
  count(Q36.Grade)
```

```{r}
CK2.1_clean %>%
  ggplot() +
  geom_bar(aes(x = Q36.Grade))
```

