---
title: "CK 5.1 Summary of Inital Answers (Winter 2021)"
author: "Rachel Roggenkemper"
date: '2022-08-09'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("~/Documents/FROST-SUMMER-2022/Winter2021")

library(tidyverse)
library(readxl)  
CK5.1 <- read_excel("FROST Grading CK 5.1_final (Winter 2021).xlsx")
```

```{r}
CK5.1_clean = subset(CK5.1, select = -c(Student:GroupCK.5.1))

CK5.1_clean <- drop_na(CK5.1_clean)

colnames(CK5.1_clean)[2] <- "Q15_1.Grade"
colnames(CK5.1_clean)[7] <- "Q15_2.Grade"
```

```{r}
CK5.1_all <- data.frame(unlist(CK5.1_clean))
colnames(CK5.1_all)[1] <- "Grades"
```


All Questions 
```{r}
CK5.1_all %>%
  count(Grades)
```

```{r}
CK5.1_all %>%
  ggplot() +
  geom_bar(aes(x = Grades))
```


Question 4
```{r}
CK5.1_clean %>%
  count(Q4.Grade)
```

```{r}
CK5.1_clean %>%
  ggplot() +
  geom_bar(aes(x = Q4.Grade))
```


Question 15 (Part 1)
```{r}
CK5.1_clean %>%
  count(Q15_1.Grade)
```

```{r}
CK5.1_clean %>%
  ggplot() +
  geom_bar(aes(x = Q15_1.Grade))
```


Question 6
```{r}
CK5.1_clean %>%
  count(Q6.Grade)
```

```{r}
CK5.1_clean %>%
  ggplot() +
  geom_bar(aes(x = Q6.Grade))
```


Question 8
```{r}
CK5.1_clean %>%
  count(Q8.Grade)
```

```{r}
CK5.1_clean %>%
  ggplot() +
  geom_bar(aes(x = Q8.Grade))
```


Question 9 
```{r}
CK5.1_clean %>%
  count(Q9.Grade)
```

```{r}
CK5.1_clean %>%
  ggplot() +
  geom_bar(aes(x = Q9.Grade))
```


Question 14
```{r}
CK5.1_clean %>%
  count(Q14.Grade)
```

```{r}
CK5.1_clean %>%
  ggplot() +
  geom_bar(aes(x = Q14.Grade))
```


Question 15 (Part 2)
```{r}
CK5.1_clean %>%
  count(Q15_2.Grade)
```

```{r}
CK5.1_clean %>%
  ggplot() +
  geom_bar(aes(x = Q15_2.Grade))
```


Question 17
```{r}
CK5.1_clean %>%
  count(Q17.Grade)
```

```{r}
CK5.1_clean %>%
  ggplot() +
  geom_bar(aes(x = Q17.Grade))
```


Question 18
```{r}
CK5.1_clean %>%
  count(Q18.Grade)
```

```{r}
CK5.1_clean %>%
  ggplot() +
  geom_bar(aes(x = Q18.Grade))
```



